# -*- coding: utf-8 -*-
"""2.student.mark.oop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RHrkz8CvL-PA7GuDiIythKcUgxdJOAIf
"""

class Student:
    """Class representing a student with private attributes and polymorphic methods."""
    def __init__(self, student_id="", name="", dob=""):
        self.__id = student_id
        self.__name = name
        self.__dob = dob

    def get_id(self):
        return self.__id

    def set_id(self, student_id):
        self.__id = student_id

    def get_name(self):
        return self.__name

    def set_name(self, name):
        self.__name = name

    def get_dob(self):
        return self.__dob

    def set_dob(self, dob):
        self.__dob = dob

    def input(self):
        self.__id = input("Student ID: ")
        self.__name = input("Name: ")
        self.__dob = input("DoB: ")

    def list(self):
        print(f"ID: {self.__id} | Name: {self.__name} | DoB: {self.__dob}")


class Course:
    """Class representing a course with private attributes and polymorphic methods."""
    def __init__(self, course_id="", name=""):
        self.__id = course_id
        self.__name = name

    def get_id(self):
        return self.__id

    def set_id(self, course_id):
        self.__id = course_id

    def get_name(self):
        return self.__name

    def set_name(self, name):
        self.__name = name

    def input(self):
        self.__id = input("Course ID: ")
        self.__name = input("Course name: ")

    def list(self):
        print(f"ID: {self.__id} | Course Name: {self.__name}")


class StudentMarkManagement:
    """Manager class handling student records, courses, and marks."""
    def __init__(self):
        self.__students = []
        self.__courses = []
        self.__marks = {}

    def input_students(self):
        n = int(input("Number of students: "))
        for _ in range(n):
            student = Student()
            student.input()
            self.__students.append(student)

    def input_courses(self):
        n = int(input("Number of courses: "))
        for _ in range(n):
            course = Course()
            course.input()
            self.__courses.append(course)

    def input_marks(self):
        if not self.__courses or not self.__students:
            print("Please input students and courses first.")
            return

        course_id = input("Select course ID: ")
        course_exists = any(c.get_id() == course_id for c in self.__courses)
        if not course_exists:
            print("Invalid Course ID.")
            return

        if course_id not in self.__marks:
            self.__marks[course_id] = {}

        for student in self.__students:
            mark = float(input(f"Mark for {student.get_id()}: "))
            self.__marks[course_id][student.get_id()] = mark

    def list_courses(self):
        print("\n--- Course List ---")
        for course in self.__courses:
            course.list()

    def list_students(self):
        print("\n--- Student List ---")
        for student in self.__students:
            student.list()

    def show_marks(self):
        course_id = input("Course ID: ")
        if course_id not in self.__marks or not self.__marks[course_id]:
            print("No marks recorded for this course.")
            return

        print(f"\n--- Marks for Course {course_id} ---")
        for student_id, mark in self.__marks[course_id].items():
            print(f"Student ID: {student_id} | Mark: {mark}")

if __name__ == "__main__":
    system = StudentMarkManagement()

    system.input_students()
    system.input_courses()
    system.input_marks()

    system.list_courses()
    system.list_students()
    system.show_marks()