# -*- coding: utf-8 -*-
"""labwork1b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eg77P2yotzg2cUNIOF8sYDJFJHl16H5e
"""

students = []
n = int(input("Number of students:"))
for i in range(n):
    id = input("Student ID:")
    name = input("Name:")
    dob = input("DoB:")
    students.append([id, name, dob])
courses = []
n = int(input("Number of courses:"))
for i in range(n):
    id = input("Course ID:")
    name = input("Course name:")
    courses.append([id, name])
marks = {}
course_id = input("Select course ID:")
marks[course_id] = {}
for student in students:
    mark = float(input("Mark for " + student[0] + ":"))
    marks[course_id][student[0]] = mark
def list_courses():
    for course in courses:
        print(course[0], course[1])
def list_students():
    for student in students:
        print(student[0], student[1], student[2])
def show_marks():
    course_id = input("Course ID:")
    for student_id in marks[course_id]:
        print(student_id, marks[course_id][student_id])

