# -*- coding: utf-8 -*-
"""labwork1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BWMb4kIfPqoz1SBbsB9rDvB7W4gARl2O

1.
"""

import math
r = float(input("Enter circle radius: "))
area = math.pi*r*r
print("Circle area = ",round(area))

"""2."""

c = float(input("Enter the temperature: "))
f = c*9/5*32
print(c,"C","temp is",f,"F")

"""3."""

n = int(input("Enter the number: "))
if n<2:
  print(n, "is not the prime number")
else:
  for i in range(2,n):
    if n % i == 0:
      print(n,"is the prime number")
      break
  else:
    print(n,"is the prime number")

"""4."""

n = int(input("Enter the number: "))
if n <= 0:
    print(f"{n} is not a perfect number")
else:
    total = 0
    for i in range(1, n):
        if n % i == 0:
            total = total + i
    if total == n:
        print(f"{n} is the perfect number")
    else:
        print(f"{n} is not the perfect number")

"""5."""

n = input("What is your favourite color? ")
if n == "red":
    print("your color is at index 3 in my list")
else:
    print("Sorry, I could not find your color")

"""6."""

print(list(range(7)))
print(list(range(1,11,3)))
print(list(range(5,0,-1)))
print(list(range(6,-3,-2)))

"""7."""

def remove_dollar_sign(s):
  return s.replace("$","")
s = input("enter money: " )
print(remove_dollar_sign(s))

"""8."""

def extract_even(l):
  result = []
  for x in l:
    if x % 2 == 0:
      result.append(x)
  return result
print(extract_even([1,4,5,-1,10]))

"""9."""

def factorial(n):
  result = 1
  for i in range(1,n+1):
    result *= i
  return result
print(factorial(5))

"""10."""

def divisor(n):
  result=[]
  for i in range(1,n+1):
    if n % i == 0:
      result.append(i)
  return result
print(divisor(12))

"""11."""

import math
def distance(x1,y1,x2,y2):
  return math.sqrt((x2-x1)**2+(y2-y1)**2)
print(distance(0,0,1,1))

"""12."""

def rectangle(m,n):
  for i in range(m):
    if i == 0 or i == m-1:
      print("* " * n)
    else:
      print("* "+"  "*(n-2)+"*")
rectangle(4,5)